export const ERROR_KIND_LABELS = {
  UnknownModel: 'Unknown Model',
  AiError: 'AI Error',
  TimedOut: 'Timed Out',
  TooManyBackups: 'Too Many Backups',
  InvalidPeriod: 'Invalid Period',
  MissingArg: 'Missing Arg',
  ForbiddenOutput: 'Forbidden Output',
  InvalidArgs: 'Invalid Args',
  InputNotFound: 'Input Not Found',
  FileDirNotFound: 'File Or Dir Not Found',
  InvalidFormat: 'Invalid Format',
  InvalidYaml: 'Invalid Yaml',
  GitNotFound: 'Git Not Found',
  FailFast: 'Fail Fast',
  EnvVarNotAllowed: 'Env Var Not Allowed',
  EnvVarNotSet: 'Env Var Not Set',
  InvalidPath: 'Invalid Path',
} as const;
